[2021-02-09 16:54:47] ERROR : µ¼ÈëÊ§°Ü: ¡ý 
Traceback (most recent call last):
  File "C:\Users\Administrator\niansbot\miraibot\plugin.py", line 41, in load_plugin
    module = importlib.import_module(module_name)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\niansbot\plugins\rua\__init__.py", line 1, in <module>
    from .petpet import *
  File "C:\Users\Administrator\niansbot\plugins\rua\petpet.py", line 8, in <module>
    from miraibot import judge
ImportError: cannot import name 'judge' from 'miraibot' (C:\Users\Administrator\niansbot\miraibot\__init__.py)

